name: zoomvtools

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Run rustfmt
        run: |
          cargo fmt -- --check

  clippy:
    needs: [rustfmt]
    strategy:
      matrix:
        platform: [ubuntu-latest, ubuntu-24.04-arm]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      # - uses: ilammy/setup-nasm@v1

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy --tests --benches -- -D warnings

  test:
    needs: [clippy]
    strategy:
      matrix:
        platform: [ubuntu-latest]
    # FIXME: run tests on ARM and Windows

    runs-on: ${{ matrix.platform }}
    container: shssoichiro/av1an-ci:latest

    steps:
      - uses: actions/checkout@v4
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      # - name: Set MSVC x86_64 linker path
      #   if: matrix.platform == 'windows-latest'
      #   run: |
      #     $LinkGlob = "VC\Tools\MSVC\*\bin\Hostx64\x64"
      #     $env:PATH = "$env:PATH;${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer"
      #     $LinkPath = vswhere -latest -products * -find "$LinkGlob" |
      #                 Select-Object -Last 1
      #     echo "$LinkPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run tests
        run: cargo test

      - name: Generate docs
        run: cargo doc --no-deps

  code-coverage:
    needs: [test]
    runs-on: ubuntu-latest
    container: shssoichiro/av1an-ci:latest

    steps:
      - uses: actions/checkout@v4
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --lcov --output-path lcov.log

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.log
          fail_ci_if_error: false
